export { default as Acrobat } from './Acrobat';
export { default as AfterEffects } from './AfterEffects';
export { default as CreativeCloud } from './CreativeCloud';
export { default as Figma } from './Figma';
export { default as GoogleSlides } from './GoogleSlides';
export { default as Illustrator } from './Illustrator';
export { default as Indesign } from './Indesign';
export { default as LightRoom } from './LightRoom';
export { default as PowerPoint } from './PowerPoint';
